name = "PIVProcessing"
uuid = "85b15f1c-7089-46bd-92e8-f6a88ea5eb9c"
authors = ["Luciano <lhergenreder@uc.cl> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
